import React from 'react'

const Index = () => {
    return (
        <main className='w-full mt-[8vh] py-20 flex flex-col justify-center items-center'>

            <div className='w-full flex flex-col justify-start items-center space-y-4 px-5 md:px-10 lg:px-20 pb-20'>
                <h3 className='text-black text-3xl lg:text-5xl font-bold mb-5'>  PDF Crops & Your Privacy </h3>
                <p className='text-gray-500 text-base font-medium'>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, laudantium quis. Nisi excepturi soluta eligendi cupiditate dolore culpa eius laborum delectus quasi rem aliquam ipsam, voluptatem odit sapiente quidem ipsum eveniet pariatur eos sequi dolor velit. Natus et quos saepe tempora excepturi nesciunt vel rem totam pariatur magni, voluptatum unde nulla adipisci quisquam cum dolor aliquam cumque necessitatibus minima. Perspiciatis illo fuga quisquam provident voluptatem libero nostrum tempora molestiae dignissimos, magnam ab ex saepe quaerat soluta quibusdam aut. Odio tempore at corporis ducimus? Assumenda enim repellat perferendis sed, sequi ex omnis? Accusamus cum deserunt hic maiores repellat! Sint, in. Dolorem rerum mollitia repudiandae minus accusantium adipisci maiores, sed dolores, possimus nam quidem optio tempora beatae quisquam sint dignissimos suscipit aliquid neque maxime odio! Voluptas molestiae eius, quidem officia quod laborum at dolor eveniet? Deserunt, eaque dolorum optio suscipit nulla odit fuga placeat possimus quidem ullam expedita repellat vitae laboriosam? Saepe dolores suscipit, in eius quo eveniet sequi, sapiente totam ad facere non illum, reiciendis itaque soluta quas labore nisi exercitationem error est nulla! Accusantium sequi aliquid consequatur ut quod omnis culpa voluptatum perspiciatis a, nulla ullam saepe quos nesciunt hic recusandae ipsam tempore molestiae, dignissimos explicabo iste ratione necessitatibus magnam. Laborum quod sint odio nisi, aut vel nihil voluptate? Architecto vitae id similique velit minus ea voluptate pariatur provident, magni iusto, deleniti laboriosam atque magnam eius unde. Dignissimos amet veritatis laborum assumenda fuga consequatur unde ipsa sint a illum vero aspernatur doloremque magnam perferendis hic deserunt voluptatum voluptate nam suscipit possimus architecto earum, accusantium ad? Natus consequuntur non sit, laudantium earum officia eligendi quibusdam repellat delectus assumenda dignissimos corporis qui accusantium libero eveniet inventore voluptates ad quam ab aliquid laboriosam? Optio voluptate ad vitae aliquam quidem animi nisi necessitatibus aperiam totam, eaque, molestiae tenetur hic inventore incidunt unde ea cupiditate!
                </p>

                <p className='text-gray-500 text-base font-medium my-10'>
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, laudantium quis. Nisi excepturi soluta eligendi cupiditate dolore culpa eius laborum delectus quasi rem aliquam ipsam, voluptatem odit sapiente quidem ipsum eveniet pariatur eos sequi dolor velit. Natus et quos saepe tempora excepturi nesciunt vel rem totam pariatur magni, voluptatum unde nulla adipisci quisquam cum dolor aliquam cumque necessitatibus minima. Perspiciatis illo fuga quisquam provident voluptatem libero nostrum tempora molestiae dignissimos, magnam ab ex saepe quaerat soluta quibusdam aut. Odio tempore at corporis ducimus? Assumenda enim repellat perferendis sed, sequi ex omnis? Accusamus cum deserunt hic maiores repellat! Sint, in. Dolorem rerum mollitia repudiandae minus accusantium adipisci maiores, sed dolores, possimus nam quidem optio tempora beatae quisquam sint dignissimos suscipit aliquid neque maxime odio! Voluptas molestiae eius, quidem officia quod laborum at dolor eveniet? Deserunt, eaque dolorum optio suscipit nulla odit fuga placeat possimus quidem ullam expedita repellat vitae laboriosam? Saepe dolores suscipit, in eius quo eveniet sequi, sapiente totam ad facere non illum, reiciendis itaque soluta quas labore nisi exercitationem error est nulla! Accusantium sequi aliquid consequatur ut quod omnis culpa voluptatum perspiciatis a, nulla ullam saepe quos nesciunt hic recusandae ipsam tempore molestiae, dignissimos explicabo iste ratione necessitatibus magnam. Laborum quod sint odio nisi, aut vel nihil voluptate? Architecto vitae id similique velit minus ea voluptate pariatur provident, magni iusto, deleniti laboriosam atque magnam eius unde. Dignissimos amet veritatis laborum assumenda fuga consequatur unde ipsa sint a illum vero aspernatur doloremque magnam perferendis hic deserunt voluptatum voluptate nam suscipit possimus architecto earum, accusantium ad? Natus consequuntur non sit, laudantium earum officia eligendi quibusdam repellat delectus assumenda dignissimos corporis qui accusantium libero eveniet inventore voluptates ad quam ab aliquid laboriosam? Optio voluptate ad vitae aliquam quidem animi nisi necessitatibus aperiam totam, eaque, molestiae tenetur hic inventore incidunt unde ea cupiditate!
                </p>
            </div>

        </main>
    )
}

export default Index