import React, { useEffect } from 'react'
import Footer from '@/components/global/Footer/Footer'
import Header from '@/components/global/Header/Header'
import Sidebar from '@/components/global/Sidebar/Sidebar'
import Head from 'next/head'
import { PDFcropSiteOptions } from '@/constants/PDFcropSiteOptions/PDFcropSiteOptions'

const BaseOneLayout = ({ children }) => {


    useEffect(() => {
        if(!window.localStorage.getItem("selectedSiteDetails")) {
            window.localStorage.setItem("selectedSiteDetails", JSON.stringify(PDFcropSiteOptions[0]))
        }

    },[])


    return (
        <div className='w-full h-auto bg-gray-100 flex flex-col justify-start items-center overflow-x-hidden overflow-y-scroll'>
            <Head>
                <title> PDF Crops </title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            {/* <Sidebar /> */}

            {children}
            <Footer />

        </div>
    )
}

export default BaseOneLayout