import Head from 'next/head'
import React from 'react'

const BaseOneLayout = ({ children }) => {
    return (
        <div className='w-full h-screen bg-red-300 flex flex-col justify-start items-center'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {children}

        </div>
    )
}

export default BaseOneLayout