import Footer from '@/components/global/Footer/Footer'
import Header from '@/components/global/Header/Header'
import Sidebar from '@/components/global/Sidebar/Sidebar'
import Head from 'next/head'
import React from 'react'

const BaseOneLayout = ({ children }) => {
    return (
        <div className='w-full h-auto bg-white flex flex-col justify-start items-center overflow-x-hidden overflow-y-scroll'>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            {/* <Sidebar /> */}

            {children}
            <Footer />

        </div>
    )
}

export default BaseOneLayout